const defaults={income:10700,fixed:6180,saving:1120};
const defaultBudgets=[{name:'Lebensmittel',limit:900},{name:'Shopping',limit:500},{name:'Transport',limit:450},{name:'Freizeit',limit:350},{name:'Abonnements',limit:180}];
let settings=JSON.parse(localStorage.getItem('bq_settings')||'null')||defaults;
let budgets=JSON.parse(localStorage.getItem('bq_budgets')||'null')||defaultBudgets;
let tx=JSON.parse(localStorage.getItem('bq_tx')||'[]');
let household=localStorage.getItem('bq_household')||'BudgetQuest';
let xp=Number(localStorage.getItem('bq_xp')||2480),csvRows=[],setupFiles=[],setupAnalysis=null,undoItem=null,undoTimer=null;
budgets=budgets.map(b=>({name:b.name,limit:+b.limit||0}));
const $=id=>document.getElementById(id),money=v=>'CHF '+Number(v||0).toLocaleString('de-CH',{maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const parseDate=v=>{if(!v)return null;let s=String(v).trim();const m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);if(m)s=`${m[3].length===2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?null:d};
const monthTx=(month=new Date().getMonth(),year=new Date().getFullYear())=>tx.filter(t=>{const d=parseDate(t.date);return d&&d.getMonth()===month&&d.getFullYear()===year});
const monthSpent=(month,year)=>monthTx(month,year).reduce((s,t)=>s+(+t.amount>0?+t.amount:0),0);
function saveAll(){localStorage.setItem('bq_settings',JSON.stringify(settings));localStorage.setItem('bq_budgets',JSON.stringify(budgets));localStorage.setItem('bq_tx',JSON.stringify(tx));localStorage.setItem('bq_xp',xp);localStorage.setItem('bq_household',household)}
function categorySpent(name){return monthTx().filter(t=>t.cat===name&&+t.amount>0).reduce((s,t)=>s+(+t.amount||0),0)}
function savingRate(){const spent=monthSpent()+Number(settings.fixed||0);return settings.income?Math.max(-100,Math.round((settings.income-spent)/settings.income*100)):0}
function score(){const total=budgets.reduce((s,b)=>s+b.limit,0),variable=monthSpent(),budgetScore=total?Math.max(0,1-variable/total):1,rate=Math.max(0,savingRate())/40;return Math.max(0,Math.min(100,Math.round(55+budgetScore*25+Math.min(1,rate)*20)))}
function render(){const variable=monthSpent(),available=settings.income-settings.fixed-variable,totalOut=settings.fixed+variable,rate=savingRate(),financialScore=score();$('householdTitle').textContent=household;$('incomeHero').textContent=money(available);$('heroSpent').textContent=`${money(totalOut)} Ausgaben diesen Monat`;$('scoreRing').style.setProperty('--p',financialScore);$('scoreValue').textContent=financialScore;$('incomeMetric').textContent=money(settings.income);$('expenseMetric').textContent=money(totalOut);$('savingRateMetric').textContent=rate+' %';$('levelBadge').textContent=`Level ${Math.floor(xp/400)+1} · ${xp.toLocaleString('de-CH')} XP`;$('incomeInput').value=settings.income;$('fixedInput').value=settings.fixed;$('savingInput').value=settings.saving;$('goalValue').textContent=money(settings.saving);$('budgetList').innerHTML=budgets.map(b=>budgetCard(b,false)).join('');$('budgetList2').innerHTML=budgets.map((b,i)=>budgetCard(b,true,i)).join('');$('txCategory').innerHTML=$('receiptCategory').innerHTML=budgets.map(b=>`<option>${esc(b.name)}</option>`).join('');$('txDate').value=new Date().toISOString().slice(0,10);renderTransactions();renderChart();renderInsights();fillYears();renderStats()}
function budgetCard(b,edit,i){const spent=categorySpent(b.name),p=b.limit?Math.min(100,spent/b.limit*100):0;return`<div class="budget-item"><div class="metric-line"><strong>${esc(b.name)}</strong><span>${money(spent)} / ${money(b.limit)}</span></div><div class="progress"><span style="width:${p}%"></span></div>${edit?`<div class="actions"><button class="btn secondary" onclick="editBudget(${i})">Bearbeiten</button><button class="btn danger" onclick="deleteBudget(${i})">Löschen</button></div>`:''}</div>`}
function renderTransactions(){const sorted=tx.map((t,i)=>({...t,_i:i})).sort((a,b)=>(parseDate(b.date)||0)-(parseDate(a.date)||0));$('transactionsList').innerHTML=sorted.length?sorted.map(t=>`<div class="transaction-shell" data-index="${t._i}"><div class="delete-bg">Löschen</div><div class="transaction"><div><div class="tx-title">${esc(t.title)}</div><div class="tx-meta">${esc(t.cat||'Nicht zugeordnet')} · ${esc(t.date||'')}</div></div><strong class="${+t.amount<0?'positive':'negative'}">${+t.amount<0?'+':'-'}${money(Math.abs(t.amount))}</strong></div></div>`).join(''):'<div class="empty">Noch keine Buchungen.</div>';bindSwipe()}
function bindSwipe(){document.querySelectorAll('.transaction-shell').forEach(shell=>{const row=shell.querySelector('.transaction');let start=0,delta=0,active=false;row.addEventListener('pointerdown',e=>{start=e.clientX;active=true;row.setPointerCapture(e.pointerId)});row.addEventListener('pointermove',e=>{if(!active)return;delta=Math.min(0,Math.max(-120,e.clientX-start));row.style.transform=`translateX(${delta}px)`});const finish=()=>{if(!active)return;active=false;if(delta<-72){row.style.transform='translateX(-120px)';setTimeout(()=>removeTransaction(+shell.dataset.index),100)}else row.style.transform='translateX(0)';delta=0};row.addEventListener('pointerup',finish);row.addEventListener('pointercancel',finish)})}
function removeTransaction(index){undoItem={item:tx[index],index};tx.splice(index,1);saveAll();render();showUndo()}
function showUndo(){clearTimeout(undoTimer);$('toast').classList.add('show');undoTimer=setTimeout(()=>{$('toast').classList.remove('show');undoItem=null},5000)}
$('undoBtn').onclick=()=>{if(!undoItem)return;tx.splice(undoItem.index,0,undoItem.item);undoItem=null;clearTimeout(undoTimer);$('toast').classList.remove('show');saveAll();render()};
function renderChart(){const now=new Date(),vals=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),monthRows=monthTx(d.getMonth(),d.getFullYear()),income=monthRows.filter(t=>+t.amount<0).reduce((s,t)=>s+Math.abs(+t.amount),0)||Number(settings.income),expenses=monthRows.filter(t=>+t.amount>0).reduce((s,t)=>s+(+t.amount),0)+Number(settings.fixed);vals.push({label:d.toLocaleDateString('de-CH',{month:'short'}),income,expenses})}const max=Math.max(1,...vals.flatMap(v=>[v.income,v.expenses]));$('monthChart').innerHTML=vals.map(v=>`<div class="month-bar"><div class="bar-pair"><div class="bar income" style="height:${v.income/max*100}%"></div><div class="bar expense" style="height:${v.expenses/max*100}%"></div></div><span class="month-label">${v.label}</span></div>`).join('')}
function renderInsights(){const current=monthSpent(),prevDate=new Date(new Date().getFullYear(),new Date().getMonth()-1,1),prev=monthSpent(prevDate.getMonth(),prevDate.getFullYear()),diff=prev?Math.round((current-prev)/prev*100):0,top=budgets.map(b=>({name:b.name,value:categorySpent(b.name)})).sort((a,b)=>b.value-a.value)[0];$('insights').innerHTML=`<div class="insight"><strong>${diff<=0?'📉 Gute Entwicklung':'📈 Ausgaben gestiegen'}</strong><div class="tiny">${prev?`${Math.abs(diff)} % ${diff<=0?'weniger':'mehr'} als im Vormonat.`:'Noch kein Vormonatsvergleich verfügbar.'}</div></div><div class="insight"><strong>🎯 Sparquote ${savingRate()} %</strong><div class="tiny">${savingRate()>=20?'Starke Sparquote.':'Nächstes Etappenziel: 20 %.'}</div></div><div class="insight"><strong>🛒 Top-Kategorie: ${esc(top?.name||'–')}</strong><div class="tiny">${money(top?.value||0)} im aktuellen Monat.</div></div>`}
function saveSettings(e){e.preventDefault();settings={income:+$('incomeInput').value,fixed:+$('fixedInput').value,saving:+$('savingInput').value};saveAll();render()}
function addBudget(e){e.preventDefault();budgets.push({name:$('newCat').value.trim(),limit:+$('newLimit').value});e.target.reset();saveAll();render()}
function editBudget(i){const n=prompt('Kategoriename',budgets[i].name),l=n===null?null:prompt('Monatslimit',budgets[i].limit);if(n!==null&&l!==null&&!isNaN(+l)){budgets[i]={name:n.trim()||budgets[i].name,limit:Math.max(0,+l)};saveAll();render()}}
function deleteBudget(i){if(confirm('Kategorie löschen?')){budgets.splice(i,1);saveAll();render()}}
function addTransaction(e){e.preventDefault();tx.push({title:$('txTitle').value.trim(),amount:+$('txAmount').value,cat:$('txCategory').value,date:$('txDate').value});xp+=20;e.target.reset();$('txDialog').close();saveAll();render()}
function fillYears(){const years=new Set([new Date().getFullYear()]);tx.forEach(t=>{const d=parseDate(t.date);if(d)years.add(d.getFullYear())});const selected=+$('yearSelect').value||new Date().getFullYear();$('yearSelect').innerHTML=[...years].sort((a,b)=>b-a).map(y=>`<option ${selected===y?'selected':''}>${y}</option>`).join('')}
function renderStats(){if(!$('yearSelect').options.length)return;const year=+$('yearSelect').value,months=Array(12).fill(0);tx.forEach(t=>{const d=parseDate(t.date);if(d&&d.getFullYear()===year&&+t.amount>0)months[d.getMonth()]+=+t.amount});const total=months.reduce((a,b)=>a+b,0),active=months.filter(Boolean),avg=active.length?total/active.length:0,min=active.length?Math.min(...active):0,names=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];$('yearExpense').textContent=money(total);$('monthAverage').textContent=money(avg);$('bestMonth').textContent=active.length?names[months.indexOf(min)]:'–';$('yearChart').innerHTML=months.map((v,i)=>`<div class="month-bar"><div class="bar-pair"><div class="bar expense" style="height:${Math.max(2,v/Math.max(...months,1)*100)}%"></div></div><span class="month-label">${names[i]}</span></div>`).join('')}
function guessCategory(name){return /(migros|coop|denner|aldi|lidl|volg|spar|avec)/i.test(name)?'Lebensmittel':/(shell|esso|avia|bp|agrola|sbb|parking|tank)/i.test(name)?'Transport':/(netflix|spotify|disney|apple\.com\/bill|swisscom|sunrise|salt)/i.test(name)?'Abonnements':/(restaurant|mcdonald|burger|pizzeria|cafe|kaffee)/i.test(name)?'Restaurant':/(ikea|jumbo|manor|zara|h&m|galaxus|digitec)/i.test(name)?'Shopping':'Sonstiges'}
function parseAmount(s){let v=String(s??'').trim().replace(/\s/g,'').replace(/CHF/ig,'');if(!v)return NaN;if(v.includes(',')&&v.includes('.'))v=v.lastIndexOf(',')>v.lastIndexOf('.')?v.replace(/\./g,'').replace(',','.'):v.replace(/,/g,'');else v=v.replace(/'/g,'').replace(',','.');return Number(v.replace(/[^0-9.+-]/g,''))}
function splitCsvLine(line,sep){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
function parseCsv(text,fileName='Bank.csv'){const lines=String(text).replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)return[];const candidates=[';','\t',','],sep=candidates.sort((a,b)=>(lines[0].split(b).length-lines[0].split(a).length))[0],headers=splitCsvLine(lines[0],sep).map(h=>h.toLowerCase().trim());const find=patterns=>headers.findIndex(h=>patterns.some(p=>h.includes(p)));const dateI=find(['buchungsdatum','valutadatum','datum','date']),textI=find(['buchungstext','beschreibung','details','mitteilung','empfänger','auftraggeber','merchant','text']),amountI=find(['betrag','amount','umsatz']),debitI=find(['belastung','debit','soll']),creditI=find(['gutschrift','credit','haben']);return lines.slice(1).map((line,i)=>{const c=splitCsvLine(line,sep);let amount=amountI>=0?parseAmount(c[amountI]):NaN;if(!Number.isFinite(amount)){const debit=debitI>=0?parseAmount(c[debitI]):NaN,credit=creditI>=0?parseAmount(c[creditI]):NaN;amount=Number.isFinite(debit)&&debit!==0?Math.abs(debit):Number.isFinite(credit)&&credit!==0?-Math.abs(credit):NaN}const title=(textI>=0?c[textI]:'')||c.find((v,j)=>j!==dateI&&j!==amountI&&/[A-Za-zÄÖÜäöü]{3}/.test(v))||'Bankbuchung';const d=parseDate(dateI>=0?c[dateI]:'');return Number.isFinite(amount)&&d?{title:title.trim(),amount,date:d.toISOString().slice(0,10),cat:guessCategory(title),source:'csv',file:fileName,row:i}:null}).filter(Boolean)}
async function filesToRows(files){const arrays=await Promise.all([...files].map(f=>f.text().then(t=>parseCsv(t,f.name))));return arrays.flat()}
function normalMerchant(s){return String(s).toLowerCase().replace(/\b(chf|kartenzahlung|e-banking|zahlung|lastschrift|gutschrift|rechnung)\b/g,'').replace(/[0-9*.,:/_-]+/g,' ').replace(/\s+/g,' ').trim().slice(0,45)}
function analyseRows(rows){const monthKeys=[...new Set(rows.map(r=>r.date.slice(0,7)))],months=Math.max(1,monthKeys.length);const incomes=rows.filter(r=>r.amount<0&&!/(übertrag|transfer|umbuchung)/i.test(r.title));const incomeByMonth={};incomes.forEach(r=>incomeByMonth[r.date.slice(0,7)]=(incomeByMonth[r.date.slice(0,7)]||0)+Math.abs(r.amount));const monthlyIncome=Object.values(incomeByMonth).length?Object.values(incomeByMonth).reduce((a,b)=>a+b,0)/Object.values(incomeByMonth).length:0;const expenses=rows.filter(r=>r.amount>0&&!/(übertrag|transfer|umbuchung)/i.test(r.title));const groups={};expenses.forEach(r=>{const k=normalMerchant(r.title)||r.title;(groups[k]??=[]).push(r)});let fixed=0;const fixedRows=[];Object.entries(groups).forEach(([k,list])=>{const activeMonths=new Set(list.map(r=>r.date.slice(0,7))).size,avg=list.reduce((s,r)=>s+r.amount,0)/list.length,variance=list.reduce((s,r)=>s+Math.abs(r.amount-avg),0)/list.length;if(activeMonths>=Math.min(3,Math.max(2,Math.ceil(months*.45)))&&variance<=Math.max(8,avg*.18)){fixed+=list.reduce((s,r)=>s+r.amount,0)/months;fixedRows.push({name:k,monthly:list.reduce((s,r)=>s+r.amount,0)/months})}});const fixedSet=new Set(fixedRows.map(x=>x.name)),catTotals={};expenses.forEach(r=>{if(fixedSet.has(normalMerchant(r.title)))return;catTotals[r.cat]=(catTotals[r.cat]||0)+r.amount/months});const proposed=Object.entries(catTotals).filter(([,v])=>v>=15).sort((a,b)=>b[1]-a[1]).map(([name,v])=>({name,limit:Math.ceil(v/50)*50}));return{rows,months,monthlyIncome:Math.round(monthlyIncome),fixed:Math.round(fixed),saving:Math.max(0,Math.round((monthlyIncome-fixed)*.15/50)*50),budgets:proposed.length?proposed:defaultBudgets,fixedRows}}
function setupNext(step){document.querySelectorAll('.wizard-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===step));document.querySelectorAll('.steps span').forEach((s,i)=>s.classList.toggle('on',i<step))}
function handleSetupFiles(files){setupFiles=[...files];$('setupFileList').innerHTML=setupFiles.map(f=>`<div class="file-item"><span>📄 ${esc(f.name)}</span><small>${(f.size/1024).toFixed(0)} KB</small></div>`).join('');$('analyseBtn').disabled=!setupFiles.length}
async function analyseSetup(){setupNext(3);const stages=[['Bankdateien werden gelesen…',22,'Dateien geladen'],['Buchungen werden kategorisiert…',50,'Kategorien erkannt'],['Einnahmen und Fixkosten werden gesucht…',78,'Wiederkehrende Zahlungen erkannt'],['Budgets werden berechnet…',100,'Budgetvorschläge erstellt']];$('analysisChecks').innerHTML='';for(const [text,p,label] of stages){$('analysisText').textContent=text;$('analysisBar').style.width=p+'%';await new Promise(r=>setTimeout(r,380));$('analysisChecks').innerHTML+=`<div class="check-item"><span>✓ ${label}</span></div>`}const rows=await filesToRows(setupFiles);setupAnalysis=analyseRows(rows);showSetupReview();setTimeout(()=>setupNext(4),300)}
function showSetupReview(){const a=setupAnalysis;$('setupIncome').value=a.monthlyIncome;$('setupFixed').value=a.fixed;$('setupSaving').value=a.saving;$('setupCategories').innerHTML=`<div class="tiny">${a.rows.length} Buchungen aus ${a.months} Monaten · ${a.fixedRows.length} Fixkosten erkannt</div>`+a.budgets.map(b=>`<div class="category-review"><span>${esc(b.name)}</span><span>${money(b.limit)}/Monat</span></div>`).join('')}
function finishSetup(){if(!setupAnalysis)return;household=$('setupHousehold').value.trim()||'Unser Haushalt';settings={income:+$('setupIncome').value||0,fixed:+$('setupFixed').value||0,saving:+$('setupSaving').value||0};budgets=setupAnalysis.budgets;tx=mergeTransactions(tx,setupAnalysis.rows);localStorage.setItem('bq_setup_done','1');saveAll();$('setupWizard').hidden=true;render()}
function mergeTransactions(existing,incoming){const seen=new Set(existing.map(r=>`${r.date}|${Math.round(+r.amount*100)}|${normalMerchant(r.title)}`));return existing.concat(incoming.filter(r=>{const k=`${r.date}|${Math.round(+r.amount*100)}|${normalMerchant(r.title)}`;if(seen.has(k))return false;seen.add(k);return true}))}
function restartSetup(){if(confirm('Ersteinrichtung erneut starten? Bestehende Daten bleiben bis zur Bestätigung erhalten.')){$('setupWizard').hidden=false;setupNext(1)}}
async function readCsvFiles(files){$('csvStatus').textContent='Dateien werden gelesen…';csvRows=await filesToRows(files);$('csvStatus').textContent=`${csvRows.length} Buchungen erkannt.`;$('importCsvBtn').disabled=!csvRows.length}
function importCsv(){tx=mergeTransactions(tx,csvRows);saveAll();render();$('csvStatus').textContent=`Import abgeschlossen. ${csvRows.length} Zeilen geprüft.`;csvRows=[]}
function prepareImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,900/img.width),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c)};img.onerror=reject;img.src=url})}
function extractFast(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),known=['Migros','Coop','Denner','Aldi','Lidl','Volg','Spar','Jumbo','IKEA','Digitec','Galaxus','Manor'];let merchant=known.find(k=>new RegExp(k,'i').test(text))||lines.find(x=>/[A-Za-zÄÖÜäöü]{3}/.test(x)&&!/(quittung|kassenbon|beleg|total|summe|mwst)/i.test(x))||'Beleg';let totals=[];lines.filter(l=>/total|summe|betrag|zu zahlen|endbetrag/i.test(l)).forEach(l=>(l.match(/\d{1,5}[.,]\d{2}/g)||[]).forEach(n=>totals.push(parseAmount(n))));return{merchant,amount:Math.max(...totals.filter(Number.isFinite),0),cat:guessCategory(merchant)}}
async function scanReceipt(file){if(!file)return;$('receiptPreview').src=URL.createObjectURL(file);$('receiptPreview').hidden=false;$('receiptForm').hidden=true;$('receiptStatus').textContent='Beleg wird vorbereitet…';try{const result=await Tesseract.recognize(await prepareImage(file),'deu'),d=extractFast(result.data.text);$('receiptMerchant').value=d.merchant;$('receiptAmount').value=d.amount||'';$('receiptCategory').value=budgets.some(b=>b.name===d.cat)?d.cat:(budgets[0]?.name||'');$('receiptForm').hidden=false;$('receiptStatus').textContent=d.amount?'Fertig – bitte kurz prüfen.':'Total bitte manuell ergänzen.'}catch(e){$('receiptStatus').textContent='Scan fehlgeschlagen: '+e.message}}
function saveReceipt(e){e.preventDefault();tx.push({title:$('receiptMerchant').value.trim(),amount:+$('receiptAmount').value,cat:$('receiptCategory').value,date:new Date().toISOString().slice(0,10),source:'receipt'});xp+=25;saveAll();render();$('receiptDialog').close();e.target.reset();$('receiptPreview').hidden=true}
document.querySelectorAll('.nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$(btn.dataset.target).classList.add('active');scrollTo({top:0,behavior:'smooth'})});
if(!localStorage.getItem('bq_setup_done'))$('setupWizard').hidden=false;if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');render();