(()=>{
const baseParseAmount=window.parseAmount,baseSplit=window.splitCsvLine;
const smartDate=v=>{if(!v)return null;let s=String(v).trim();const m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);if(m)s=`${m[3].length===2?'20'+m[3]:m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const d=new Date(s);return isNaN(d)?null:d};
const salarySources=[
 {name:'Oberholzer AG',owner:'Ismael Heusser',kind:'Hauptlohn',pattern:/oberholzer ag/i},
 {name:'Ärztefon AG',owner:'Sarah Heusser',kind:'Lohn',pattern:/aerztefon|ärztefon|arztefon/i},
 {name:'Kinderpraxis Uster',owner:'Sarah Heusser',kind:'Lohn',pattern:/kinderpraxis uster|stephanie stücheli/i},
 {name:'Diakoniewerk Neumünster',owner:'Sarah Heusser',kind:'Lohn',pattern:/stiftung diakoniewerk neumünster|stiftung diakoniewerk neumunster|schweizerische pflegerinnen/i}
];
const salaryWords=/\blohn\b|gehalt|sal[aä]r|payroll|13\.\s*monatslohn/i;
const rules={
 saving:[/übertrag auf (mitglieder|geschenk)?sparkonto/i,/dauerauftrag sparkonto darlehen/i,/sparauftrag|einzahlung.*3a|säule 3a/i],
 transfer:[/übertrag von (mitglieder|geschenk)?sparkonto/i,/revolut bank|revolut\*\*/i,/zufluss vom hauptkonto/i,/umbuchung|kontoübertrag|interner übertrag/i,/gutschrift.*heuss(er|er, ismael)|gutschrift ismael stefan heusser/i],
 investment:[/vreneli|edelmetall|goldkauf|silber|depotkauf|wertschriftenkauf|etf kauf/i],
 refund:[/rückerstattung|rückvergütung|storno|retoure|gutschrift.*(digitec|galaxus|dosenbach|buttinette|mobiliar|agrisano|krankenkasse)/i],
 capital:[/zinsgutschrift|dividende|coupon|kapitalertrag/i]
};
const categoryRules=[
 ['Lebensmittel',/migros|coop|denner|aldi|lidl|volg|landi laden|konditorei|bäckerei|baeckerei|fontis|vuaillat|gwunderchischte/i],
 ['Restaurant / Auswärts essen',/restaurant|pizzeria|cafe|café|cafeteria|mcdonald|burger|take.?away|badi gossau/i],
 ['Transport / Auto',/parkingpay|sbb|tankstelle|agrola|socar|eni |avia|shell|bp |amag|garage|treibstoff/i],
 ['Gesundheit / Versicherung',/krankenkasse|versicherung|mobiliar|agrisano|osteopath|ostheopath|arzt|apotheke|drogerie|zahnarzt|spital/i],
 ['Telekom / Abos / Digital',/swisscom|sunrise|salt|netflix|spotify|disney|apple\.com\/bill|microsoft|google|adobe|hosting/i],
 ['Shopping / Diverses',/digitec|galaxus|ikea|jumbo|manor|dosenbach|ochsner|decathlon|ifolor|buttinette|amazon|zalando|h&m|zara/i],
 ['Haustiere',/qualipet|fressnapf|tierarzt|veterin/i],
 ['Freizeit / Reisen',/schwingklub|hotel|airbnb|booking|freizeitpark|tierpark|kino|museum|ferien|reise/i],
 ['Bildung / Kinder',/schule|kita|kindergarten|agando ministries|kurs|ausbildung|musikschule/i],
 ['Steuern / Gemeinde',/steuer|gemeinde|kanton|bundessteuer|gebühr/i],
 ['Spenden / Kirche',/kirche|gemeinde moenchaltorf|spende|mission/i],
 ['Kreditkarte (Cembra)',/cembra/i],['Privatzahlungen (P2P)',/zahlung twint/i]
];
function classify(title,internalAmount){const s=String(title||'').trim(),source=salarySources.find(x=>x.pattern.test(s));let type='expense',budgetEffect=true,category='Sonstiges',confidence=.72,incomeSource='',incomeKind='',incomeOwner='';
 if(rules.saving.some(r=>r.test(s))){type='saving';budgetEffect=false;category='Sparen / interner Übertrag';confidence=.99}
 else if(rules.transfer.some(r=>r.test(s))){type='transfer';budgetEffect=false;category=/von .*sparkonto|gutschrift/i.test(s)?'Rückübertrag von Sparkonto':'Interner Übertrag';confidence=.98}
 else if(rules.investment.some(r=>r.test(s))){type='investment';budgetEffect=false;category='Edelmetalle / Anlage';confidence=.96}
 else if(rules.refund.some(r=>r.test(s))){type='refund';category='Rückerstattung';confidence=.95}
 else if(rules.capital.some(r=>r.test(s))){type='capital_income';category='Kapitalertrag';confidence=.95}
 else if(source&&internalAmount<0){type='salary';category='Lohn';incomeSource=source.name;incomeKind=source.kind;incomeOwner=source.owner;confidence=.995}
 else if(salaryWords.test(s)&&internalAmount<0){type='salary';category='Lohn';incomeSource=s;incomeKind='Ungeprüfter Lohn';confidence=.88}
 else if(internalAmount<0){type='other_credit';category='Sonstige Gutschrift';confidence=.75}
 else{for(const [cat,re] of categoryRules)if(re.test(s)){category=cat;confidence=.9;break}}
 return{type,category,budgetEffect,confidence,incomeSource,incomeKind,incomeOwner}}
function normaliseAmount(raw,title,debit=false,credit=false){const n=Math.abs(Number(raw));if(!Number.isFinite(n))return NaN;if(debit)return n;if(credit)return-n;if(/gutschrift|lohn|gehalt|sal[aä]r|zahlungseingang|eingang|rückerstattung|rückvergütung/i.test(title)||salarySources.some(x=>x.pattern.test(title)))return-n;return Number(raw)<0?n:-n}
window.classifyBudgetQuestTransaction=classify;
window.parseCsv=function(text,fileName='Bank.csv'){const lines=String(text).replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)return[];const candidates=[';','\t',','],sep=candidates.sort((a,b)=>lines[0].split(b).length-lines[0].split(a).length)[0],headers=baseSplit(lines[0],sep).map(h=>h.toLowerCase().trim()),find=ps=>headers.findIndex(h=>ps.some(p=>h.includes(p)));const dateI=find(['buchungsdatum','valutadatum','datum','date']),textI=find(['buchungstext','beschreibung','details','mitteilung','empfänger','auftraggeber','merchant','text']),amountI=find(['betrag','amount','umsatz']),debitI=find(['belastung','debit','soll']),creditI=find(['gutschrift','credit','haben']);return lines.slice(1).map((line,i)=>{const c=baseSplit(line,sep),title=((textI>=0?c[textI]:'')||c.find((v,j)=>j!==dateI&&/[A-Za-zÄÖÜäöü]{3}/.test(v))||'Bankbuchung').trim();let amount=NaN;const debit=debitI>=0?baseParseAmount(c[debitI]):NaN,credit=creditI>=0?baseParseAmount(c[creditI]):NaN,raw=amountI>=0?baseParseAmount(c[amountI]):NaN;if(Number.isFinite(debit)&&debit!==0)amount=normaliseAmount(debit,title,true,false);else if(Number.isFinite(credit)&&credit!==0)amount=normaliseAmount(credit,title,false,true);else if(Number.isFinite(raw)&&raw!==0)amount=normaliseAmount(raw,title);const d=smartDate(dateI>=0?c[dateI]:'');if(!Number.isFinite(amount)||!d)return null;const cl=classify(title,amount);return{title,amount,date:d.toISOString().slice(0,10),cat:cl.category,type:cl.type,budgetEffect:cl.budgetEffect,confidence:cl.confidence,incomeSource:cl.incomeSource,incomeKind:cl.incomeKind,incomeOwner:cl.incomeOwner,source:'csv',file:fileName,row:i}}).filter(Boolean)};
window.analyseRows=function(rows){const budgetRows=rows.filter(r=>r.budgetEffect!==false),months=Math.max(1,new Set(rows.map(r=>r.date.slice(0,7))).size),salaries=budgetRows.filter(r=>r.type==='salary'),expenses=budgetRows.filter(r=>r.type==='expense'),byMonth={};salaries.forEach(r=>byMonth[r.date.slice(0,7)]=(byMonth[r.date.slice(0,7)]||0)+Math.abs(r.amount));const vals=Object.values(byMonth),monthlyIncome=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0,fixedCats=new Set(['Gesundheit / Versicherung','Telekom / Abos / Digital','Steuern / Gemeinde','Kreditkarte (Cembra)']);let fixed=expenses.filter(r=>fixedCats.has(r.cat)).reduce((s,r)=>s+Math.abs(r.amount),0)/months;const catTotals={};expenses.filter(r=>!fixedCats.has(r.cat)).forEach(r=>catTotals[r.cat]=(catTotals[r.cat]||0)+Math.abs(r.amount)/months);const budgets=Object.entries(catTotals).filter(([,v])=>v>=15).sort((a,b)=>b[1]-a[1]).map(([name,v])=>({name,limit:Math.ceil(v/50)*50})),excluded=rows.filter(r=>r.budgetEffect===false),counts=rows.reduce((a,r)=>(a[r.type]=(a[r.type]||0)+1,a),{}),incomeMap={};salaries.forEach(r=>{const key=r.incomeSource||r.title;(incomeMap[key]??={name:key,owner:r.incomeOwner||'',kind:r.incomeKind||'Lohn',total:0,count:0});incomeMap[key].total+=Math.abs(r.amount);incomeMap[key].count++});const incomeBreakdown=Object.values(incomeMap).sort((a,b)=>b.total-a.total);return{rows,months,monthlyIncome:Math.round(monthlyIncome),fixed:Math.round(fixed),saving:Math.round(excluded.filter(r=>r.type==='saving').reduce((s,r)=>s+Math.abs(r.amount),0)/months),budgets:budgets.length?budgets:defaultBudgets,fixedRows:[],excluded,counts,incomeBreakdown}};
const oldShow=window.showSetupReview;window.showSetupReview=function(){oldShow();const a=setupAnalysis;if(!a)return;const incomeHtml=(a.incomeBreakdown||[]).map(x=>`<div class="category-review"><span>${esc(x.name)}<small style="display:block">${esc(x.owner||x.kind)} · ${x.count} Lohnbuchungen</small></span><span>${money(x.total/a.months)}/Monat</span></div>`).join('');document.getElementById('setupCategories').insertAdjacentHTML('afterbegin',`<div class="info-note"><strong>Lohn-Assistent</strong><br>Es werden nur erkannte Lohnzahlungen für das Monatseinkommen verwendet.<br>Rückerstattungen, Transfers, Zinsen, Dividenden und andere Gutschriften zählen nicht als Lohn.</div>${incomeHtml?`<h3 style="margin-top:18px">Erkannte Lohnquellen</h3>${incomeHtml}`:'<div class="info-note">Keine eindeutigen Lohnzahlungen erkannt. Bitte Einkommen manuell prüfen.</div>'}`)};
const oldFinish=window.finishSetup;window.finishSetup=function(){if(setupAnalysis){const excluded=setupAnalysis.rows.filter(r=>r.budgetEffect===false);localStorage.setItem('bq_transfer_ledger',JSON.stringify(excluded));localStorage.setItem('bq_income_sources',JSON.stringify(setupAnalysis.incomeBreakdown||[]));setupAnalysis.rows=setupAnalysis.rows.filter(r=>r.budgetEffect!==false)}oldFinish()};
const oldRead=window.readCsvFiles;window.readCsvFiles=async function(files){await oldRead(files);const excluded=csvRows.filter(r=>r.budgetEffect===false),included=csvRows.filter(r=>r.budgetEffect!==false);window.__bqExcluded=excluded;csvRows=included;const counts=[...included,...excluded].reduce((a,r)=>(a[r.type]=(a[r.type]||0)+1,a),{});document.getElementById('csvStatus').innerHTML=`<strong>${included.length} budgetwirksame Buchungen</strong><br>${counts.salary||0} erkannte Lohnzahlungen · ${counts.expense||0} Ausgaben<br>${counts.other_credit||0} sonstige Gutschriften werden nicht als Lohn gezählt.`};
const oldImport=window.importCsv;window.importCsv=function(){const ledger=JSON.parse(localStorage.getItem('bq_transfer_ledger')||'[]');if(window.__bqExcluded?.length)localStorage.setItem('bq_transfer_ledger',JSON.stringify(ledger.concat(window.__bqExcluded)));oldImport();window.__bqExcluded=[]};
})();

(()=>{
let receiptQueue=[],activeReceipt=null,activeObjectUrl='';
const PDF_VERSION='4.10.38';
const PDF_MODULE=`https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${PDF_VERSION}/pdf.min.mjs`;
const PDF_WORKER=`https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${PDF_VERSION}/pdf.worker.min.mjs`;
async function loadPdfJs(){if(window.pdfjsLib){window.pdfjsLib.GlobalWorkerOptions.workerSrc=PDF_WORKER;return window.pdfjsLib}try{const mod=await import(PDF_MODULE);window.pdfjsLib=mod;mod.GlobalWorkerOptions.workerSrc=PDF_WORKER;return mod}catch(e){throw new Error('PDF-Modul konnte nicht geladen werden.')}}
async function pdfToCanvas(file){const pdfjs=await loadPdfJs(),data=await file.arrayBuffer(),pdf=await pdfjs.getDocument({data}).promise,page=await pdf.getPage(1),viewport=page.getViewport({scale:1.7}),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=Math.round(viewport.width);canvas.height=Math.round(viewport.height);await page.render({canvasContext:ctx,viewport}).promise;return canvas}
async function fileToCanvas(file){return file.type==='application/pdf'||/\.pdf$/i.test(file.name)?pdfToCanvas(file):prepareImage(file)}
function setupImportUi(){const dialog=document.getElementById('receiptDialog');if(!dialog||dialog.dataset.smartImport==='1')return;dialog.dataset.smartImport='1';dialog.querySelector('h3').textContent='Beleg importieren';dialog.querySelector('p').textContent='Kamera, Fotos und PDF-Rechnungen werden per Texterkennung ausgewertet.';const oldDrop=dialog.querySelector('.dropzone');oldDrop.outerHTML=`<div class="import-source-grid"><label class="dropzone">📷 Kamera<input type="file" accept="image/*" capture="environment" onchange="importReceiptFiles(this.files)"></label><label class="dropzone">🖼 Fotos<input type="file" accept="image/*" multiple onchange="importReceiptFiles(this.files)"></label><label class="dropzone">📄 PDF<input type="file" accept="application/pdf,.pdf" multiple onchange="importReceiptFiles(this.files)"></label></div>`;const button=document.querySelector('[onclick="receiptDialog.showModal()"]');if(button)button.textContent='➕ Importieren';const form=document.getElementById('receiptForm');form.insertAdjacentHTML('beforeend','<div id="receiptQueueInfo" class="tiny"></div>')}
function updateQueueInfo(){const el=document.getElementById('receiptQueueInfo');if(el)el.textContent=receiptQueue.length?`${receiptQueue.length} weitere Datei(en) warten.`:''}
async function processNext(){if(activeReceipt||!receiptQueue.length)return;activeReceipt=receiptQueue.shift();updateQueueInfo();const status=document.getElementById('receiptStatus'),preview=document.getElementById('receiptPreview'),form=document.getElementById('receiptForm');form.hidden=true;preview.hidden=true;status.textContent=`${activeReceipt.name} wird ausgewertet…`;try{const canvas=await fileToCanvas(activeReceipt);activeObjectUrl=canvas.toDataURL('image/jpeg',.86);preview.src=activeObjectUrl;preview.hidden=false;const result=await Tesseract.recognize(canvas,'deu'),d=extractFast(result.data.text);document.getElementById('receiptMerchant').value=d.merchant;document.getElementById('receiptAmount').value=d.amount||'';document.getElementById('receiptCategory').value=budgets.some(b=>b.name===d.cat)?d.cat:(budgets[0]?.name||'');form.hidden=false;status.textContent=d.amount?'Erkannt – bitte prüfen und übernehmen.':'Betrag nicht sicher erkannt – bitte ergänzen.'}catch(e){form.hidden=true;preview.hidden=true;status.textContent='Import fehlgeschlagen: '+e.message;activeReceipt=null;processNext()}}
window.importReceiptFiles=function(files){receiptQueue.push(...Array.from(files||[]).filter(f=>f.type.startsWith('image/')||f.type==='application/pdf'||/\.pdf$/i.test(f.name)));updateQueueInfo();processNext()};
const oldSave=window.saveReceipt;window.saveReceipt=function(e){oldSave(e);activeReceipt=null;setTimeout(()=>{if(receiptQueue.length){document.getElementById('receiptDialog').showModal();processNext()}},80)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupImportUi);else setupImportUi();
})();