const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const source=fs.readFileSync('legacy-backup-import.js','utf8');
const store=new Map();
const context={window:null,document:{getElementById:()=>null},setInterval(fn){this._fn=fn;return 1},clearInterval(){},budgetQuestStorage:{get:(k,d)=>store.has(k)?store.get(k):d,set:(k,v)=>store.set(k,v)},BudgetQuestStorageKeys:{sharedRevision:'rev'},importHousehold(){},console};
context.window=context;
vm.runInNewContext(source,context);
context._fn();
const backup={format:'budgetquest-household',version:3,appVersion:20,revision:3,household:'Familie Heusser',profiles:[{id:'isme',name:'Ismael',emoji:'👤'}],activeProfileId:'isme',settings:{income:14528.33,fixed:6500,saving:3800},budgets:[{name:'Lebensmittel',limit:1400}],transactions:[{title:'Migros',amount:136.4,cat:'Lebensmittel',date:'2026-07-24'}],xp:2595,homePlan:{equity:143000,annualGross:174340,monthlySaving:3800,pillar3aBalance:118000,pillar3aMode:'withdraw'},wealth:{cash:110000,pillar3a:118000,stocks:18000,other:15000},incomePlan:{people:[]},budgetStart:'2026-07-01'};
const migrated=context.BudgetQuestLegacyImport.normalizeBackup(backup);
assert.equal(migrated.homePlan.annualGross,174340);
assert.equal(migrated.homePlan.calcInterest,5);
assert.equal(migrated.wealth.pillar3a,118000);
assert.equal(migrated.transactions.length,1);
assert.equal(migrated.activeProfileId,'isme');
const missing=context.BudgetQuestLegacyImport.normalizeBackup({format:'budgetquest-household',transactions:[]});
assert.equal(missing.homePlan.annualGross,0);
assert.ok(missing.profiles.length>0);
console.log('legacy backup import: ok');
